### ISSUE TITLE
Enlace roto para la comunidad BoGOLang

### ISSUE THREAD

**Issue by CamiloBernal** [colombia-dev/colombia-dev.github.io#25]
El meetup BoGOLang no existe en el sitio de Meetup: https://www.meetup.com/BoGOLang/

**Comment by buritica** [comment]
@DavidNV ☝️

**Comment by santiaguf** [comment]
Fixed at https://github.com/colombia-dev/colombia-dev.github.io/commit/e9544f024cd17ff54761258ae6226841c476559c
