### ISSUE TITLE
Ordenar por alfabeto la lista de meetups?

### ISSUE THREAD

**Issue by goanpeca** [colombia-dev/colombia-dev.github.io#30]
Hola, en el momento no parece haber ningún orden en el listado de meetups disponibles por ciudad.

Mi sugerencia es ordenar todo por alfabeto, (ciudad y meetups) así se volvería más fácil buscar en el contenido. Si es algo que les parece adecuado, puedo abrir un PR para hacer los cambios.

**Comment by buritica** [comment]
hola, estoy pensando en actualizar el sitio completo entonces por ahora creo qeu es mucho esfuerzo reordenar. graciaspor la oferta!

**Comment by santiaguf** [comment]
Fixed at https://github.com/colombia-dev/colombia-dev.github.io/commit/d50f4ad10c27b249bdc0ac51eb31ab337e3bd884
