### ISSUE TITLE
Habilitar HTTPS (Provided by Github Pages)

### ISSUE THREAD

**Issue by jhta** [colombia-dev/colombia-dev.github.io#34]
Ahora es posible habilitar HTTPS gratis en github pages para custom domains:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Para ello en el proovedor de dominio, agregar los siguientes **A Record Points**:

| Type  | Host |                  Value |
|-------|:----:|-----------------------:|
|   A   |   @  |        185.199.108.153 |
|   A   |   @  |        185.199.109.153 |
|   A   |   @  |        185.199.110.153 |
|   A   |   @  | 185.199.111.153        |
| CNAME | WWW  | colombia-dev.github.io |

(Este cambio puede tomar tiempo dependiendo del proovedor)

Luego ir al repositorio, ir a configuración:

![image](https://user-images.githubusercontent.com/5351504/45241868-ad3ac480-b2b3-11e8-856b-973ec7bd8827.png)

Seleccionar ** enforce HTTPS **

![image](https://user-images.githubusercontent.com/5351504/45241948-e8d58e80-b2b3-11e8-9266-3321241ee619.png)

Y listo, debería de funcionar.

Tutorial detallado: https://medium.com/@anirudhgoel_54535/add-https-to-your-namecheap-domain-hosted-on-github-pages-d66fd96308b5

**Comment by buritica** [comment]
@jhta si le doy admin access al repo, se le mide?

**Comment by buritica** [comment]
ah, mentiras no es tanta vaina. ya lo hago

**Comment by jhta** [comment]
de one, en caso de que no puedas, me le mido

**Comment by buritica** [comment]
ya se esta refrescando el cert, para manana queda listo.

**Comment by buritica** [comment]
https://colombia-dev.org/, listo

**Comment by jhta** [comment]
quedo al pelo
