### ISSUE TITLE
¿Sigue activo este repo?

### ISSUE THREAD

**Issue by joelibaceta** [colombia-dev/colombia-dev.github.io#43]
El año pasado empezamos un proyecto con algunos developers en Peru inspirados en este proyecto, hemos avanzado bastante gracias a la contribución de otros devs y me gustaría poder retribuir la inspiración al proyecto original :), los invito a ver nuestro repo http://peruanos.dev

Y si aun esta este repo abierto a contribuciones me gustaría poder ayudar 👍

**Comment by buritica** [comment]
si. sigue activo pero lento :)
