### ISSUE TITLE
Idea: Aprovechar el generador de paginas de GitHub 

### ISSUE THREAD

**Issue by joelibaceta** [colombia-dev/colombia-dev.github.io#44]
Hola, estaba pensando que si se usa el generador de paginas que tiene GitHub basado en Jekyll podría simplificarse la manera de agregar nuevos meetups, podria limitarse a llenar un comunidades.json yaml o csv con un PR y cuando este llegue a master podría disparar un nuevo build y actualizar la pagina de forma automática :).

**Comment by santiaguf** [comment]
La idea está buena, y es bastante útil cuando se está empezando a crear el listado, sin embargo, para el caso de Colombia donde la mayoría de comunidades tech ya se encuentran en el listado, lo seguiremos manejando mediante PR.
